version: '3.9'
services:
  node:
    build:
      context: ./
    ports:
      - '3333:3333'
      - '8080:8080'
    container_name: adonisjs
    environment:
      - NODE_ENV=development
    volumes:
       - .:/usr/app
    #   - /usr/src/app/node_modules
    user: node
    command:
      - npm
      - run
      - dev
