version: '3.9'
services:
  node:
    build:
      context: ./
    ports:
      - '3333:3333'
      - '8080:8080'
    container_name: node-commerce
    environment:
      - NODE_ENV=development
    volumes:
       - .:/usr/app
    #   - /usr/src/app/node_modules
    user: node
    command:
      - npm
      - run
      - dev

  postgres:
    container_name: node_commerce_db
    image: postgres:12-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data
      - ./dockerConfig/postgres-dev-init.sql:/docker-entrypoint-initdb.d/init.sql # will setup dev database adonis_app for us
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  redis:
    container_name: node_commerce_redis
    image: redis:alpine
    volumes:
      - redis_volume:/data
    ports:
      - 6379:6379

volumes:
  postgres_volume:
  redis_volume:
